"""Add methods pays relationship

Revision ID: 2cd2573ff2b9
Revises: bd6a49174988
Create Date: 2025-08-14 08:50:01.282993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd2573ff2b9'
down_revision = 'bd6a49174988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membresia_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'metodo_pago', ['metodo_pago_id'], ['id'])

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'metodo_pago', ['metodo_pago_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('metodo_pago_id')

    with op.batch_alter_table('membresia_cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('metodo_pago_id')

    # ### end Alembic commands ###
