"""add soft delete

Revision ID: 987f95ac5898
Revises: 27ff047203bf
Create Date: 2025-06-07 11:39:52.691926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987f95ac5898'
down_revision = '27ff047203bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_cliente_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_detalle_venta_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('entrada_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_entrada_inventario_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('evaluacion_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_evaluacion_cliente_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventario_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('membresia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_membresia_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('membresia_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_membresia_cliente_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_producto_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_venta_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('membresia_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membresia_cliente_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('membresia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membresia_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventario_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('evaluacion_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluacion_cliente_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('entrada_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrada_inventario_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalle_venta_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
