"""Add methods pays

Revision ID: bd6a49174988
Revises: 30628bdf0015
Create Date: 2025-08-14 08:37:16.576835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6a49174988'
down_revision = 'd524af88455c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodo_pago',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metodo_pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metodo_pago_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metodo_pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metodo_pago_deleted_at'))

    op.drop_table('metodo_pago')
    # ### end Alembic commands ###
