"""active membership client

Revision ID: d524af88455c
Revises: 30628bdf0015
Create Date: 2025-08-11 17:15:53.528770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd524af88455c'
down_revision = '30628bdf0015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membresia_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membresia_cliente', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
